#version 310 es

/*
 * Copyright 2018 The GraphicsFuzz Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

layout(std430, binding = 2) buffer abuf { int data[]; };

layout(local_size_x=128, local_size_y=1) in;

void main() {
  for (uint d = gl_WorkGroupSize.x / 2u; d > 0u; d >>= 1u) {
    if (gl_LocalInvocationID.x < d) {
       data[gl_LocalInvocationID.x] += data[d + gl_LocalInvocationID.x];
    }
    barrier();
  }
}
