# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfauto/artifact.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gfauto import common_pb2 as gfauto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfauto/artifact.proto',
  package='gfauto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15gfauto/artifact.proto\x12\x06gfauto\x1a\x13gfauto/common.proto\"\xc4\x01\n\x10\x41rtifactMetadata\x12+\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1d.gfauto.ArtifactMetadata.Data\x12\x14\n\x0c\x64\x65rived_from\x18\x02 \x03(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x1a\\\n\x04\x44\x61ta\x12L\n\x15\x65xtracted_archive_set\x18\x01 \x01(\x0b\x32+.gfauto.ArtifactMetadataExtractedArchiveSetH\x00\x42\x06\n\x04\x64\x61ta\"N\n#ArtifactMetadataExtractedArchiveSet\x12\'\n\x0b\x61rchive_set\x18\x01 \x01(\x0b\x32\x12.gfauto.ArchiveSetb\x06proto3'
  ,
  dependencies=[gfauto_dot_common__pb2.DESCRIPTOR,])




_ARTIFACTMETADATA_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='gfauto.ArtifactMetadata.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extracted_archive_set', full_name='gfauto.ArtifactMetadata.Data.extracted_archive_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='gfauto.ArtifactMetadata.Data.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=159,
  serialized_end=251,
)

_ARTIFACTMETADATA = _descriptor.Descriptor(
  name='ArtifactMetadata',
  full_name='gfauto.ArtifactMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gfauto.ArtifactMetadata.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='derived_from', full_name='gfauto.ArtifactMetadata.derived_from', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='gfauto.ArtifactMetadata.comment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ARTIFACTMETADATA_DATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=251,
)


_ARTIFACTMETADATAEXTRACTEDARCHIVESET = _descriptor.Descriptor(
  name='ArtifactMetadataExtractedArchiveSet',
  full_name='gfauto.ArtifactMetadataExtractedArchiveSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='archive_set', full_name='gfauto.ArtifactMetadataExtractedArchiveSet.archive_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=331,
)

_ARTIFACTMETADATA_DATA.fields_by_name['extracted_archive_set'].message_type = _ARTIFACTMETADATAEXTRACTEDARCHIVESET
_ARTIFACTMETADATA_DATA.containing_type = _ARTIFACTMETADATA
_ARTIFACTMETADATA_DATA.oneofs_by_name['data'].fields.append(
  _ARTIFACTMETADATA_DATA.fields_by_name['extracted_archive_set'])
_ARTIFACTMETADATA_DATA.fields_by_name['extracted_archive_set'].containing_oneof = _ARTIFACTMETADATA_DATA.oneofs_by_name['data']
_ARTIFACTMETADATA.fields_by_name['data'].message_type = _ARTIFACTMETADATA_DATA
_ARTIFACTMETADATAEXTRACTEDARCHIVESET.fields_by_name['archive_set'].message_type = gfauto_dot_common__pb2._ARCHIVESET
DESCRIPTOR.message_types_by_name['ArtifactMetadata'] = _ARTIFACTMETADATA
DESCRIPTOR.message_types_by_name['ArtifactMetadataExtractedArchiveSet'] = _ARTIFACTMETADATAEXTRACTEDARCHIVESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArtifactMetadata = _reflection.GeneratedProtocolMessageType('ArtifactMetadata', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _ARTIFACTMETADATA_DATA,
    '__module__' : 'gfauto.artifact_pb2'
    # @@protoc_insertion_point(class_scope:gfauto.ArtifactMetadata.Data)
    })
  ,
  'DESCRIPTOR' : _ARTIFACTMETADATA,
  '__module__' : 'gfauto.artifact_pb2'
  # @@protoc_insertion_point(class_scope:gfauto.ArtifactMetadata)
  })
_sym_db.RegisterMessage(ArtifactMetadata)
_sym_db.RegisterMessage(ArtifactMetadata.Data)

ArtifactMetadataExtractedArchiveSet = _reflection.GeneratedProtocolMessageType('ArtifactMetadataExtractedArchiveSet', (_message.Message,), {
  'DESCRIPTOR' : _ARTIFACTMETADATAEXTRACTEDARCHIVESET,
  '__module__' : 'gfauto.artifact_pb2'
  # @@protoc_insertion_point(class_scope:gfauto.ArtifactMetadataExtractedArchiveSet)
  })
_sym_db.RegisterMessage(ArtifactMetadataExtractedArchiveSet)


# @@protoc_insertion_point(module_scope)
