# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from gfauto.common_pb2 import (
    ArchiveSet as gfauto___common_pb2___ArchiveSet,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ArtifactMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Data(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

        @property
        def extracted_archive_set(self) -> type___ArtifactMetadataExtractedArchiveSet: ...

        def __init__(self,
            *,
            extracted_archive_set : typing___Optional[type___ArtifactMetadataExtractedArchiveSet] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> ArtifactMetadata.Data: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ArtifactMetadata.Data: ...
        def HasField(self, field_name: typing_extensions___Literal[u"data",b"data",u"extracted_archive_set",b"extracted_archive_set"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data",u"extracted_archive_set",b"extracted_archive_set"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions___Literal[u"data",b"data"]) -> typing_extensions___Literal["extracted_archive_set"]: ...
    type___Data = Data

    derived_from: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    comment: typing___Text = ...

    @property
    def data(self) -> type___ArtifactMetadata.Data: ...

    def __init__(self,
        *,
        data : typing___Optional[type___ArtifactMetadata.Data] = None,
        derived_from : typing___Optional[typing___Iterable[typing___Text]] = None,
        comment : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ArtifactMetadata: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ArtifactMetadata: ...
    def HasField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"comment",b"comment",u"data",b"data",u"derived_from",b"derived_from"]) -> None: ...
type___ArtifactMetadata = ArtifactMetadata

class ArtifactMetadataExtractedArchiveSet(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def archive_set(self) -> gfauto___common_pb2___ArchiveSet: ...

    def __init__(self,
        *,
        archive_set : typing___Optional[gfauto___common_pb2___ArchiveSet] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ArtifactMetadataExtractedArchiveSet: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ArtifactMetadataExtractedArchiveSet: ...
    def HasField(self, field_name: typing_extensions___Literal[u"archive_set",b"archive_set"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"archive_set",b"archive_set"]) -> None: ...
type___ArtifactMetadataExtractedArchiveSet = ArtifactMetadataExtractedArchiveSet
