# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Binary(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    tags: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    path: typing___Text = ...
    version: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        tags : typing___Optional[typing___Iterable[typing___Text]] = None,
        path : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Binary: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Binary: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"path",b"path",u"tags",b"tags",u"version",b"version"]) -> None: ...
type___Binary = Binary

class Archive(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    url: typing___Text = ...
    output_file: typing___Text = ...
    output_directory: typing___Text = ...

    def __init__(self,
        *,
        url : typing___Optional[typing___Text] = None,
        output_file : typing___Optional[typing___Text] = None,
        output_directory : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Archive: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Archive: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"output_directory",b"output_directory",u"output_file",b"output_file",u"url",b"url"]) -> None: ...
type___Archive = Archive

class ArchiveSet(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def archives(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Archive]: ...

    @property
    def binaries(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Binary]: ...

    def __init__(self,
        *,
        archives : typing___Optional[typing___Iterable[type___Archive]] = None,
        binaries : typing___Optional[typing___Iterable[type___Binary]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ArchiveSet: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ArchiveSet: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"archives",b"archives",u"binaries",b"binaries"]) -> None: ...
type___ArchiveSet = ArchiveSet
