# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfauto/recipe.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gfauto import common_pb2 as gfauto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfauto/recipe.proto',
  package='gfauto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13gfauto/recipe.proto\x12\x06gfauto\x1a\x13gfauto/common.proto\"j\n\x06Recipe\x12V\n download_and_extract_archive_set\x18\x01 \x01(\x0b\x32*.gfauto.RecipeDownloadAndExtractArchiveSetH\x00\x42\x08\n\x06recipe\"M\n\"RecipeDownloadAndExtractArchiveSet\x12\'\n\x0b\x61rchive_set\x18\x01 \x01(\x0b\x32\x12.gfauto.ArchiveSetb\x06proto3'
  ,
  dependencies=[gfauto_dot_common__pb2.DESCRIPTOR,])




_RECIPE = _descriptor.Descriptor(
  name='Recipe',
  full_name='gfauto.Recipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='download_and_extract_archive_set', full_name='gfauto.Recipe.download_and_extract_archive_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='recipe', full_name='gfauto.Recipe.recipe',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=52,
  serialized_end=158,
)


_RECIPEDOWNLOADANDEXTRACTARCHIVESET = _descriptor.Descriptor(
  name='RecipeDownloadAndExtractArchiveSet',
  full_name='gfauto.RecipeDownloadAndExtractArchiveSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='archive_set', full_name='gfauto.RecipeDownloadAndExtractArchiveSet.archive_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=237,
)

_RECIPE.fields_by_name['download_and_extract_archive_set'].message_type = _RECIPEDOWNLOADANDEXTRACTARCHIVESET
_RECIPE.oneofs_by_name['recipe'].fields.append(
  _RECIPE.fields_by_name['download_and_extract_archive_set'])
_RECIPE.fields_by_name['download_and_extract_archive_set'].containing_oneof = _RECIPE.oneofs_by_name['recipe']
_RECIPEDOWNLOADANDEXTRACTARCHIVESET.fields_by_name['archive_set'].message_type = gfauto_dot_common__pb2._ARCHIVESET
DESCRIPTOR.message_types_by_name['Recipe'] = _RECIPE
DESCRIPTOR.message_types_by_name['RecipeDownloadAndExtractArchiveSet'] = _RECIPEDOWNLOADANDEXTRACTARCHIVESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Recipe = _reflection.GeneratedProtocolMessageType('Recipe', (_message.Message,), {
  'DESCRIPTOR' : _RECIPE,
  '__module__' : 'gfauto.recipe_pb2'
  # @@protoc_insertion_point(class_scope:gfauto.Recipe)
  })
_sym_db.RegisterMessage(Recipe)

RecipeDownloadAndExtractArchiveSet = _reflection.GeneratedProtocolMessageType('RecipeDownloadAndExtractArchiveSet', (_message.Message,), {
  'DESCRIPTOR' : _RECIPEDOWNLOADANDEXTRACTARCHIVESET,
  '__module__' : 'gfauto.recipe_pb2'
  # @@protoc_insertion_point(class_scope:gfauto.RecipeDownloadAndExtractArchiveSet)
  })
_sym_db.RegisterMessage(RecipeDownloadAndExtractArchiveSet)


# @@protoc_insertion_point(module_scope)
