# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from gfauto.common_pb2 import (
    Binary as gfauto___common_pb2___Binary,
)

from gfauto.device_pb2 import (
    DeviceList as gfauto___device_pb2___DeviceList,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Settings(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    maximum_duplicate_crashes = ... # type: int
    maximum_fuzz_failures = ... # type: int
    reduce_tool_crashes = ... # type: bool
    reduce_crashes = ... # type: bool
    reduce_bad_images = ... # type: bool

    @property
    def device_list(self) -> gfauto___device_pb2___DeviceList: ...

    @property
    def custom_binaries(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[gfauto___common_pb2___Binary]: ...

    def __init__(self,
        *,
        device_list : typing___Optional[gfauto___device_pb2___DeviceList] = None,
        custom_binaries : typing___Optional[typing___Iterable[gfauto___common_pb2___Binary]] = None,
        maximum_duplicate_crashes : typing___Optional[int] = None,
        maximum_fuzz_failures : typing___Optional[int] = None,
        reduce_tool_crashes : typing___Optional[bool] = None,
        reduce_crashes : typing___Optional[bool] = None,
        reduce_bad_images : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Settings: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"device_list"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"custom_binaries",u"device_list",u"maximum_duplicate_crashes",u"maximum_fuzz_failures",u"reduce_bad_images",u"reduce_crashes",u"reduce_tool_crashes"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"device_list",b"device_list"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"custom_binaries",b"custom_binaries",u"device_list",b"device_list",u"maximum_duplicate_crashes",b"maximum_duplicate_crashes",u"maximum_fuzz_failures",b"maximum_fuzz_failures",u"reduce_bad_images",b"reduce_bad_images",u"reduce_crashes",b"reduce_crashes",u"reduce_tool_crashes",b"reduce_tool_crashes"]) -> None: ...
