#!/usr/bin/env bash

# Copyright 2018 The GraphicsFuzz Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if test -n "${PYTHON_GF}"; then
  "${PYTHON_GF}" ${BASH_SOURCE}.py "$@"
elif type -P python3 >/dev/null; then
  python3 ${BASH_SOURCE}.py "$@"
elif type -P py >/dev/null; then
  py -3 ${BASH_SOURCE}.py "$@"
else
  python ${BASH_SOURCE}.py "$@"
fi
