#!/bin/bash

# Copyright 2018 The GraphicsFuzz Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

glslangValidator -V -o coherence.vert.spv coherence.vert
(
  echo "// This file was generated by: xxd -i coherence.vert.spv"
  xxd -i coherence.vert.spv
) > coherence_vert.inc

glslangValidator -V -o coherence.frag.spv coherence.frag
(
  echo "// This file was generated by: xxd -i coherence.frag.spv"
  xxd -i coherence.frag.spv
) > coherence_frag.inc
